name: httpclient

services:
  app:
    build: .
    depends_on:
      database:
        restart: true
        condition: service_healthy
        required: true
    networks: 
      - custom
    restart: "no"
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./test
          target: /app/test
        - action: rebuild
          path: ./tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./jest.config.ts
          target: /app/jest.config.ts
        - action: rebuild
          path: ./package.json
          target: /app/package.json

  database:
    command: ["postgres", "-c", "port=6566"]
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    healthcheck:
      test: pg_isready -h database -p 6566 -d test || exit 1
      interval: 5s
      timeout: 5s
      start_period: 5s
      start_interval: 5s
      retries: 20
    image: postgres:17-alpine
    networks: 
      - custom
    restart: on-failure:3

networks:
  custom:
    driver: bridge
